observer_velocity = [10, 0]

[[object]]
color = "red"
[object.start]
t = 1
xy = [100, 100]

[object.end]
t = 2
xy = [100, 100]


[[object]]
color = "blue"
[object.start]
t = 1
xy = [200, 200]

[object.end]
t = 2
xy = [200, 200]
