[[object]]
lifetime = [0, 10]
color = "red"
velocity = [90, 0]
xy_offset = [100, 100]

[[object]]
lifetime = [0, 10]
color = "red"
velocity = [-90, 0]
xy_offset = [100, 100]

[[object]]
lifetime = [0, 10]
color = "blue"
velocity = [0, 30]
xy_offset = [100, 100]

[[object]]
lifetime = [0, 10]
color = "green"
velocity = [65, 65]
xy_offset = [100, 100]


############# background

[[object]]
lifetime = [0, 10]
color = "green"
velocity = [0, 0]
xy_offset = [300, 300]

[[object]]
lifetime = [0, 10]
color = "green"
velocity = [0, 0]
xy_offset = [100, 300]

[[object]]
lifetime = [0, 10]
color = "green"
velocity = [0, 0]
xy_offset = [100, 100]

[[object]]
lifetime = [0, 10]
color = "green"
velocity = [0, 0]
xy_offset = [300, 100]
