c = 100

[[object]]
color = "white"
follow = "me"
path = [[100, 110, 0.1], [100, 100, 1.0], [100, 110, 2.0]]

[[object]]
color = "red"
path = [[100, 100, 0], [100, 100, 2]]

[[object]]
color = "blue"
path = [[200, 200, 0], [200, 200, 2]]

[[object]]
color = "green"
path = [[200, 100, 0], [200, 200, 2]]

[[object]]
color = "yellow"
path = [[100, 100, 0], [100, 200, 2]]

[[object]]
color = "violet"
path = [[100, 100, 0], [200, 100, 2]]
