c = 100
observer_velocity = [-80, 0]

[[object]]
color = "red"
path = [[100, 100, 1], [100, 100, 2]]

[[object]]
color = "blue"
path = [[200, 200, 1], [200, 200, 2]]

[[object]]
color = "green"
path = [[200, 100, 1], [200, 200, 2]]

[[object]]
color = "yellow"
path = [[100, 100, 1], [100, 200, 2]]

[[object]]
color = "violet"
path = [[100, 100, 1], [200, 100, 2]]
