c = 100
observer_velocity = [-80, 0]

[[object]]
color = "red"
start = [100, 100, 1]
end = [100, 100, 2]

[[object]]
color = "blue"
start = [200, 200, 1]
end = [200, 200, 2]

[[object]]
color = "green"
start = [200, 100, 1]
end = [200, 200, 2]

[[object]]
color = "yellow"
start = [100, 100, 1]
end = [100, 200, 2]

[[object]]
color = "violet"
start = [100, 100, 1]
end = [200, 100, 2]
