c = 450
tick_delta = 0.01
max_clock = 20.0

[[object]]
color = "blue"
path = [[0, 0, 0], [0, 0, 1]]
follow = "me"
clock = "yes"

[[object]]
color = "violet"
path = [[0, 0, 0], [400, 0, 1]]
clock = "yes"

# background grid:

[[object]]
color = "green"
path = [[-200, -200, -200], [-200, -200, 200]]

[[object]]
color = "green"
path = [[200, 200, -200], [200, 200, 200]]

[[object]]
color = "green"
path = [[-200, 200, -200], [-200, 200, 200]]

[[object]]
color = "green"
path = [[200, -200, -200], [200, -200, 200]]


# Whichever object you choose to follow (blue / violet), the other object should be shortened a lot across the X axis.
# Independent of the follow-object, blue and violet should move apart with the same speed.

# When following blue:
# - The green boxes should be non-deformed
# When following violet:
# - Each of the green boxes should be shortened in X (just like blue is), and
# - also the virtual box (whose 4 corners are the green boxes) should be shortened in X direction
