c = 130

[[object]]
color = "violet"
path = [[-800, 0, 1], [-800, 0, 1.3]]

[[object]]
color = "violet"
path = [[-400, 0, 1], [-400, 0, 1.3]]

[[object]]
color = "violet"
path = [[0, 0, 1], [0, 0, 1.3]]

[[object]]
color = "violet"
path = [[400, 0, 1], [400, 0, 1.3]]

[[object]]
color = "violet"
path = [[800, 0, 1], [800, 0, 1.3]]


# consider changing observers between these two:
[[object]]
color = "green"
path = [[0, 100, 0], [0, 100, 20]]
follow = "me"

[[object]]
color = "red"
path = [[0, 100, 0], [440, 100, 20]]
