c = 11

[[object]]
color = "blue"
path = [[0, 0, 0], [0, 0, 20]]

[[object]]
color = "violet"
follow = "me"
path = [[0, 20, 0], [100, 20, 10], [0, 20, 20]]

[[object]]
color = "green"
path = [[110, 0, 0], [110, 0, 100]]
