c = 160

[[object]]
color = "blue"
path = [[0, 0, -1], [0, 0, 12]]
clock = "once"

[[object]]
color = "violet"
path = [[0, 100, -1], [0, 100, 0], [400, 100, 4], [0, 100, 8], [0, 100, 12]]
clock = "once"
follow = "me"

[[object]]
color = "green"
path = [[400, 0, -1], [400, 0, 20]]
clock = "once"
