c = 25

[[object]]
color = "blue"
path = [[0, 0, 0], [0, 0, 30]]
clock = "yes"

[[object]]
color = "violet"
path = [[0, 100, 0], [200, 100, 10], [0, 100, 20], [0, 100, 30]]
clock = "yes"
follow = "me"

[[object]]
color = "green"
path = [[200, 0, 0], [200, 0, 100]]
clock = "yes"
