c = 25

[[object]]
color = "blue"
path = [[0, 0, 0], [0, 0, 20]]

[[object]]
color = "violet"
follow = "me"
path = [[0, 100, 0], [200, 100, 10], [0, 100, 20]]

[[object]]
color = "green"
path = [[200, 0, 0], [200, 0, 100]]
